### ISSUE TITLE
Minimize on start-up

### ISSUE THREAD

**Issue by pmsobrado** [tiliado/nuvola-app-google-calendar#2]
Hi, is there a way to start the app minimized to tray on startup? I added to the autostart but I get the window every time.

**Comment by pmsobrado** [comment]
Fixed by running this on startup as well:

`xdotool windowunmap $(wmctrl -l|grep "Google Calendar"|awk '{print $1}')`

You will need xdotool package.

**Comment by fenryxo** [comment]
Hello @pmsobrado. There is currently no such feature

**Comment by pmsobrado** [comment]
Never mind, I found a workaround :)

**Comment by fenryxo** [comment]
nuvola-app-google-calendar is now deprecated.
